[package]
name = "rub"
version = "0.1.0"
authors = ["Evan Simmons <evan.simmons@creditkarma.com>"]

[dependencies]
clap = "2.31.1"
futures = "0.1.18"
hyper = "0.11.22"
tokio-core = "0.1.15"
hyper-tls = "0.1.2"
